### ISSUE TITLE
请教配置问题

### ISSUE THREAD

**Issue by UVJkiNTQ** [pandadtdyy/blrec2biliup#1]
启动后的输出是这样的：

INFO:werkzeug:127.0.0.1 - - [15/Oct/2022 23:19:31] "POST /test HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2022 23:19:32] "POST /test HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [15/Oct/2022 23:19:32] "POST /test HTTP/1.1" 404 -

**Comment by pandadtdyy** [comment]
webhook.py#L135 告诉了监听端口为 27817 webhook地址应该是 http://127.0.0.1:27817/webhook 哦 好像是我的文档写错了 我修改一下

**Comment by UVJkiNTQ** [comment]
INFO:werkzeug:127.0.0.1 - - [16/Oct/2022 11:29:47] "POST /webhook HTTP/1.1" 500 -
ERROR:webhook:Exception on /webhook [POST]
Traceback (most recent call last):
  File "/home/luke/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/luke/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/luke/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/luke/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/luke/.local/lib/python3.10/site-packages/asgiref/sync.py", line 218, in __call__
    return call_result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/luke/.local/lib/python3.10/site-packages/asgiref/sync.py", line 284, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/luke/blrec2biliup/webhook.py", line 45, in recvMsg
    room_info = json.loads(room_raw[0]['json'])
IndexError: tuple index out of range

**Comment by pandadtdyy** [comment]
这是因为没有触发过LiveBeganEvent 每次触发服务会去数据库里找有当前房间 而只有LiveBeganEvent才会保存房间信息

**Comment by UVJkiNTQ** [comment]
感谢解惑，我找个没开播的挂着看看。

**Comment by UVJkiNTQ** [comment]
INFO:webhook:I:是水良不是奶良_Official开播了
ERROR:webhook:Exception on /webhook [POST]
Traceback (most recent call last):
  File "/home/luke/.pyenv/versions/webhook/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/luke/.pyenv/versions/webhook/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/luke/.pyenv/versions/webhook/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/luke/.pyenv/versions/webhook/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/luke/.pyenv/versions/webhook/lib/python3.10/site-packages/asgiref/sync.py", line 218, in __call__
    return call_result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/luke/.pyenv/versions/webhook/lib/python3.10/site-packages/asgiref/sync.py", line 284, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/luke/blrec2biliup/webhook.py", line 57, in recvMsg
    with open('./' + room_id + '-' + event['date'].split(":")[0] +'.jpg','wb') as f:
TypeError: can only concatenate str (not "int") to str
INFO:werkzeug:127.0.0.1 - - [16/Oct/2022 19:07:24] "POST /webhook HTTP/1.1" 500 -

**Comment by UVJkiNTQ** [comment]
看起来是room_id的int类型的问题？

**Comment by pandadtdyy** [comment]
早期版本传的是str的room_id 可能现在改了吧

**Comment by UVJkiNTQ** [comment]
所以作者现在不在使用这个了吗？

**Comment by pandadtdyy** [comment]
这个脚本原本是用来每次一下播就上传保证录播组能不被撞车的，但是到后面会和直播录像撞车，后来就变成每次传每小时分割一次的版本了，不再需要脚本自动化。

**Comment by UVJkiNTQ** [comment]
经测试，只要将两处int转成str，依旧可用。
稍后PR。
